%% @generated by rebar3_erli18n_codegen — DO NOT EDIT.
%%
%% Compile-time erli18n catalog for module erli18n_cc_default__en.
%% An already-parsed entry list plus an already-compiled plural rule,
%% baked into BEAM so boot performs no .po parse and no plural compile.
%% Regenerate from the source .po; manual edits will be overwritten.

-module(erli18n_cc_default__en).
-export([catalog/0]).
-erli18n_compiled_catalog([{domain, 'default'},
                           {locale, <<101,110>>},
                           {generator_vsn, <<49>>}]).
-spec catalog() -> erli18n_server:compiled_spec().
catalog() ->
    {'default',
     <<101,110>>,
     [{singular, undefined,
       <<72,101,108,108,111>>,
       <<72,101,108,108,111>>},
      {singular,
       <<109,101,110,117>>,
       <<70,105,108,101>>,
       <<70,105,108,101>>}],
     #{divergence => none,
       fuzzy_included => false,
       num_entries => 2,
       plural => fallback,
       plural_raw =>
           <<110,112,108,117,114,97,108,115,61,50,59,32,112,
             108,117,114,97,108,61,40,110,32,33,61,32,49,
             41,59>>,
       po_path =>
           <<112,114,105,118,47,108,111,99,97,108,101,47,
             101,110,47,76,67,95,77,69,83,83,65,71,69,83,
             47,100,101,102,97,117,108,116,46,112,111>>}}.
